"""empty message

Revision ID: 83af09e8c8c2
Revises: 
Create Date: 2023-03-06 12:10:10.744304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83af09e8c8c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
